
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('58','26','df_diagonal','0')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('74','26','df_diagonal','0')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('74','24','df_warranty','0')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('74','27','df_cpu','0')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('59','27','df_cpu','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('59','28','df_screenresolution','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('74','28','df_screenresolution','0')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('65','25','df_principle_set','9')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('68','27','df_cpu','16')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('74','19','df_color',';;')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('59','19','df_color',';;')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('64','19','df_color',';6;')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('58','28','df_screenresolution','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('57','29','df_specification','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('65','27','df_cpu','17')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('68','24','df_warranty','0')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('55','29','df_specification','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('54','25','df_principle_set','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('54','27','df_cpu','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('54','28','df_screenresolution','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('54','26','df_diagonal','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('54','24','df_warranty','0')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('54','29','df_specification','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('54','19','df_color',';;')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('56','29','df_specification','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('55','28','df_screenresolution','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('55','19','df_color',';;')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('55','25','df_principle_set','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('55','26','df_diagonal','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('55','24','df_warranty','0')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('55','27','df_cpu','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('56','27','df_cpu','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('56','28','df_screenresolution','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('56','26','df_diagonal','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('56','24','df_warranty','0')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('56','19','df_color',';;')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('56','25','df_principle_set','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('57','27','df_cpu','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('57','28','df_screenresolution','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('57','26','df_diagonal','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('57','24','df_warranty','0')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('57','19','df_color',';;')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('57','25','df_principle_set','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('74','25','df_principle_set','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('58','19','df_color',';;')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('58','27','df_cpu','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('59','25','df_principle_set','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('68','28','df_screenresolution','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('65','24','df_warranty','30')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('68','19','df_color',';2;')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('58','29','df_specification','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('58','24','df_warranty','0')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('65','19','df_color',';2;5;')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('58','25','df_principle_set','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('64','27','df_cpu','19')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('59','24','df_warranty','0')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('74','29','df_specification','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('64','25','df_principle_set','8')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('64','24','df_warranty','0')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('64','28','df_screenresolution','22')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('65','28','df_screenresolution','22')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('68','25','df_principle_set','8')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('68','29','df_specification','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('65','29','df_specification','/catalog/demos/Test.pdf')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('59','26','df_diagonal','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('59','29','df_specification','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('64','29','df_specification','')###qb_delimiter###
INSERT INTO `#__goods_data`(`obj_id`,`field_id`,`field_name`,`field_value`) VALUES('64','30','df_certificate','6d09387c02b2f0d2e7fcefc6af9860601613518627.png')###qb_delimiter###


