
INSERT INTO `#__goods_group`(`ggr_id`,`ggr_id_parent`,`ggr_name`,`ggr_alias`,`ggr_thumb`,`ggr_title_thm`,`ggr_alt_thm`,`ggr_image`,`ggr_title_img`,`ggr_alt_img`,`ggr_image_inherit`,`ggr_comment`,`ggr_meta_title`,`ggr_meta_description`,`ggr_meta_keywords`,`ggr_ordering`,`ggr_default_sorting`,`ggr_list_tmpl`,`ggr_enabled`,`ggr_deleted`,`ggr_extcode`,`ggr_change_date`,`ggr_change_uid`) VALUES('139','0','Компьютеры и комплектующие','kompyuteri-i-komplektuyushchie','2d03ce9484ee819e4e08ab7994c548911592411063.jpg','','','6ae11478609214a1672e1df76ecfbf911592411063.jpg','','','0','<p>Компьютеры прочно вошли в жизнь любого человека.</p>

<p>Самые современные компьютеры и комплектующие представлены в данной категории.</p>

<p>Принтеры, мониторы, клавиатуры, джойстики и многое другое.</p>','Компьютеры и комплектующие','Компьютеры,комплектующие,периферия','компьютеры,комплектующие,периферия','0','','defl','1','0',NULL,'2020-06-17 19:24:23','14')###qb_delimiter###
INSERT INTO `#__goods_group`(`ggr_id`,`ggr_id_parent`,`ggr_name`,`ggr_alias`,`ggr_thumb`,`ggr_title_thm`,`ggr_alt_thm`,`ggr_image`,`ggr_title_img`,`ggr_alt_img`,`ggr_image_inherit`,`ggr_comment`,`ggr_meta_title`,`ggr_meta_description`,`ggr_meta_keywords`,`ggr_ordering`,`ggr_default_sorting`,`ggr_list_tmpl`,`ggr_enabled`,`ggr_deleted`,`ggr_extcode`,`ggr_change_date`,`ggr_change_uid`) VALUES('149','139','Компьютеры в сборе','kompyuteri-v-sbore','4a71b99eb7faa17fd1439e57d8557fae1592411081.jpg','','','58b4670409e86c89055d5ff6b4a600741592411081.jpg','','','0','','','','','0','','defl','1','0',NULL,'2021-02-04 00:41:15','14')###qb_delimiter###
INSERT INTO `#__goods_group`(`ggr_id`,`ggr_id_parent`,`ggr_name`,`ggr_alias`,`ggr_thumb`,`ggr_title_thm`,`ggr_alt_thm`,`ggr_image`,`ggr_title_img`,`ggr_alt_img`,`ggr_image_inherit`,`ggr_comment`,`ggr_meta_title`,`ggr_meta_description`,`ggr_meta_keywords`,`ggr_ordering`,`ggr_default_sorting`,`ggr_list_tmpl`,`ggr_enabled`,`ggr_deleted`,`ggr_extcode`,`ggr_change_date`,`ggr_change_uid`) VALUES('152','140','Операционные системы','operatsionnie-sistemi','c6e7ddbef1c96da596808e001197f9ad1592411264.png','','','e9fc89b6d2047324afeb134cb6e6f3cb1592411264.png','','','0','','','','','0','','defl','1','0',NULL,'2020-06-17 19:27:44','14')###qb_delimiter###
INSERT INTO `#__goods_group`(`ggr_id`,`ggr_id_parent`,`ggr_name`,`ggr_alias`,`ggr_thumb`,`ggr_title_thm`,`ggr_alt_thm`,`ggr_image`,`ggr_title_img`,`ggr_alt_img`,`ggr_image_inherit`,`ggr_comment`,`ggr_meta_title`,`ggr_meta_description`,`ggr_meta_keywords`,`ggr_ordering`,`ggr_default_sorting`,`ggr_list_tmpl`,`ggr_enabled`,`ggr_deleted`,`ggr_extcode`,`ggr_change_date`,`ggr_change_uid`) VALUES('153','140','Офисные приложения','ofisnie-prilozheniya','63ce572c5b963580406d10155179de6b1592411280.jpg','','','8fb985fd74ba05cb6453707535c578f91592411280.jpg','','','0','','','','','0','','defl','1','0',NULL,'2020-06-17 19:28:00','14')###qb_delimiter###
INSERT INTO `#__goods_group`(`ggr_id`,`ggr_id_parent`,`ggr_name`,`ggr_alias`,`ggr_thumb`,`ggr_title_thm`,`ggr_alt_thm`,`ggr_image`,`ggr_title_img`,`ggr_alt_img`,`ggr_image_inherit`,`ggr_comment`,`ggr_meta_title`,`ggr_meta_description`,`ggr_meta_keywords`,`ggr_ordering`,`ggr_default_sorting`,`ggr_list_tmpl`,`ggr_enabled`,`ggr_deleted`,`ggr_extcode`,`ggr_change_date`,`ggr_change_uid`) VALUES('154','140','Игры','igri','94c58908fdf96133d8e6194a28e636ad1592411297.jpg','','','6d005b8648299a7eb431535e0c1e32c41592411297.jpg','','','0','','','','','0','','defl','1','0',NULL,'2020-06-17 19:28:17','14')###qb_delimiter###
INSERT INTO `#__goods_group`(`ggr_id`,`ggr_id_parent`,`ggr_name`,`ggr_alias`,`ggr_thumb`,`ggr_title_thm`,`ggr_alt_thm`,`ggr_image`,`ggr_title_img`,`ggr_alt_img`,`ggr_image_inherit`,`ggr_comment`,`ggr_meta_title`,`ggr_meta_description`,`ggr_meta_keywords`,`ggr_ordering`,`ggr_default_sorting`,`ggr_list_tmpl`,`ggr_enabled`,`ggr_deleted`,`ggr_extcode`,`ggr_change_date`,`ggr_change_uid`) VALUES('140','0','Программное обеспечение','programmnoe-obespechenie','f5490119a8232314b2d268f3165904331592411101.jpg','','','aeff2c9f06a75648925d2e5b7f24850a1592411101.jpg','','','0','<p>Программы и утилиты на любой вкус.</p>

<p>Антивирусы, операционные системы, текстовые редакторы, игры.</p>','Программы и утилиты','','','0','','defl','1','0',NULL,'2020-06-17 19:25:01','14')###qb_delimiter###
INSERT INTO `#__goods_group`(`ggr_id`,`ggr_id_parent`,`ggr_name`,`ggr_alias`,`ggr_thumb`,`ggr_title_thm`,`ggr_alt_thm`,`ggr_image`,`ggr_title_img`,`ggr_alt_img`,`ggr_image_inherit`,`ggr_comment`,`ggr_meta_title`,`ggr_meta_description`,`ggr_meta_keywords`,`ggr_ordering`,`ggr_default_sorting`,`ggr_list_tmpl`,`ggr_enabled`,`ggr_deleted`,`ggr_extcode`,`ggr_change_date`,`ggr_change_uid`) VALUES('156','0','Удаленная группа товара','udalennaya-gruppa-tovara','','','','','','','0','','','','','0','','','0','1',NULL,'2019-10-18 19:07:31','14')###qb_delimiter###
INSERT INTO `#__goods_group`(`ggr_id`,`ggr_id_parent`,`ggr_name`,`ggr_alias`,`ggr_thumb`,`ggr_title_thm`,`ggr_alt_thm`,`ggr_image`,`ggr_title_img`,`ggr_alt_img`,`ggr_image_inherit`,`ggr_comment`,`ggr_meta_title`,`ggr_meta_description`,`ggr_meta_keywords`,`ggr_ordering`,`ggr_default_sorting`,`ggr_list_tmpl`,`ggr_enabled`,`ggr_deleted`,`ggr_extcode`,`ggr_change_date`,`ggr_change_uid`) VALUES('157','0','Удаленная включенная группа товара','157-udalennaya-gruppa-tovara','','','','','','','0','','','','','0','','','1','1',NULL,'2019-10-18 19:08:06','14')###qb_delimiter###
INSERT INTO `#__goods_group`(`ggr_id`,`ggr_id_parent`,`ggr_name`,`ggr_alias`,`ggr_thumb`,`ggr_title_thm`,`ggr_alt_thm`,`ggr_image`,`ggr_title_img`,`ggr_alt_img`,`ggr_image_inherit`,`ggr_comment`,`ggr_meta_title`,`ggr_meta_description`,`ggr_meta_keywords`,`ggr_ordering`,`ggr_default_sorting`,`ggr_list_tmpl`,`ggr_enabled`,`ggr_deleted`,`ggr_extcode`,`ggr_change_date`,`ggr_change_uid`) VALUES('158','154','Тестовая группа 1','testovaya-gruppa-1','','','','','','','0','','','','','0','','','1','0',NULL,'2021-02-21 00:35:52','14')###qb_delimiter###
INSERT INTO `#__goods_group`(`ggr_id`,`ggr_id_parent`,`ggr_name`,`ggr_alias`,`ggr_thumb`,`ggr_title_thm`,`ggr_alt_thm`,`ggr_image`,`ggr_title_img`,`ggr_alt_img`,`ggr_image_inherit`,`ggr_comment`,`ggr_meta_title`,`ggr_meta_description`,`ggr_meta_keywords`,`ggr_ordering`,`ggr_default_sorting`,`ggr_list_tmpl`,`ggr_enabled`,`ggr_deleted`,`ggr_extcode`,`ggr_change_date`,`ggr_change_uid`) VALUES('159','154','Тестовая группа 2','testovaya-gruppa-2','','','','','','','0','','','','','0','','','1','0',NULL,'2021-02-21 00:36:00','14')###qb_delimiter###
INSERT INTO `#__goods_group`(`ggr_id`,`ggr_id_parent`,`ggr_name`,`ggr_alias`,`ggr_thumb`,`ggr_title_thm`,`ggr_alt_thm`,`ggr_image`,`ggr_title_img`,`ggr_alt_img`,`ggr_image_inherit`,`ggr_comment`,`ggr_meta_title`,`ggr_meta_description`,`ggr_meta_keywords`,`ggr_ordering`,`ggr_default_sorting`,`ggr_list_tmpl`,`ggr_enabled`,`ggr_deleted`,`ggr_extcode`,`ggr_change_date`,`ggr_change_uid`) VALUES('160','154','Тестовая группа 3','testovaya-gruppa-3','','','','','','','0','','','','','0','','','1','0',NULL,'2021-02-21 00:36:08','14')###qb_delimiter###
INSERT INTO `#__goods_group`(`ggr_id`,`ggr_id_parent`,`ggr_name`,`ggr_alias`,`ggr_thumb`,`ggr_title_thm`,`ggr_alt_thm`,`ggr_image`,`ggr_title_img`,`ggr_alt_img`,`ggr_image_inherit`,`ggr_comment`,`ggr_meta_title`,`ggr_meta_description`,`ggr_meta_keywords`,`ggr_ordering`,`ggr_default_sorting`,`ggr_list_tmpl`,`ggr_enabled`,`ggr_deleted`,`ggr_extcode`,`ggr_change_date`,`ggr_change_uid`) VALUES('161','152','Тестовая группа 4','testovaya-gruppa-4','','','','','','','0','','','','','0','','','1','0',NULL,'2021-02-21 02:27:32','14')###qb_delimiter###
INSERT INTO `#__goods_group`(`ggr_id`,`ggr_id_parent`,`ggr_name`,`ggr_alias`,`ggr_thumb`,`ggr_title_thm`,`ggr_alt_thm`,`ggr_image`,`ggr_title_img`,`ggr_alt_img`,`ggr_image_inherit`,`ggr_comment`,`ggr_meta_title`,`ggr_meta_description`,`ggr_meta_keywords`,`ggr_ordering`,`ggr_default_sorting`,`ggr_list_tmpl`,`ggr_enabled`,`ggr_deleted`,`ggr_extcode`,`ggr_change_date`,`ggr_change_uid`) VALUES('162','152','Тестовая группа 5','testovaya-gruppa-5','','','','','','','0','','','','','0','','','1','0',NULL,'2021-02-21 02:27:39','14')###qb_delimiter###


