
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('1','0','1','read','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('1','0','1','write','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('1','0','1','moderate','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('1','0','1','postvote','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('1','0','2','read','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('1','0','2','write','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('1','0','2','moderate','0')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('1','0','2','postvote','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('1','0','3','read','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('1','0','4','read','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('1','0','4','write','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('1','0','4','moderate','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('1','0','4','postvote','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('2','0','1','read','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('2','0','1','write','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('2','0','1','moderate','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('2','0','1','postvote','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('2','0','2','read','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('2','0','2','write','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('2','0','2','postvote','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('2','0','3','read','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('2','0','4','read','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('2','0','4','write','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('2','0','4','moderate','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('2','0','4','postvote','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('3','0','1','read','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('3','0','2','read','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('3','0','3','read','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('3','0','4','read','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('4','0','1','read','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('4','0','2','read','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('4','0','3','read','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('4','0','4','read','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('4','0','1','write','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('4','0','2','write','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('4','0','4','write','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('3','0','1','write','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('3','0','2','write','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('3','0','4','write','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('3','0','1','moderate','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('3','0','4','moderate','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('4','0','1','moderate','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('4','0','4','moderate','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('3','0','1','postvote','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('3','0','2','postvote','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('3','0','4','postvote','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('4','0','1','postvote','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('4','0','2','postvote','1')###qb_delimiter###
INSERT INTO `#__forum_rights`(`f_id`,`u_id`,`r_id`,`action`,`flag`) VALUES('4','0','4','postvote','1')###qb_delimiter###


