TRUNCATE TABLE `#__menus`###qb_delimiter###
INSERT INTO `#__menus`(`mi_id`,`mi_parent_id`,`mi_name`,`mi_type`,`mi_target`,`mi_nofollow`,`mi_link`,`mi_canonical_id`,`mi_module`,`mi_view`,`mi_layout`,`mi_alias`,`mi_psid`,`mi_controller`,`mi_task`,`mi_ordering`,`mi_thumb`,`mi_image`,`mi_descr`,`mi_custom_template`,`mi_enabled`,`mi_deleted`,`mi_access`,`mi_forlang`) VALUES('28','7','Дерево статей','0','window','0','','0','article','tree','','','0','','','4','','','','','1','0','all','all')###qb_delimiter###
INSERT INTO `#__menus`(`mi_id`,`mi_parent_id`,`mi_name`,`mi_type`,`mi_target`,`mi_nofollow`,`mi_link`,`mi_canonical_id`,`mi_module`,`mi_view`,`mi_layout`,`mi_alias`,`mi_psid`,`mi_controller`,`mi_task`,`mi_ordering`,`mi_thumb`,`mi_image`,`mi_descr`,`mi_custom_template`,`mi_enabled`,`mi_deleted`,`mi_access`,`mi_forlang`) VALUES('27','7','Список статей','0','window','0','','0','article','list','','','0','','','3','','','','','1','0','all','all')###qb_delimiter###
INSERT INTO `#__menus`(`mi_id`,`mi_parent_id`,`mi_name`,`mi_type`,`mi_target`,`mi_nofollow`,`mi_link`,`mi_canonical_id`,`mi_module`,`mi_view`,`mi_layout`,`mi_alias`,`mi_psid`,`mi_controller`,`mi_task`,`mi_ordering`,`mi_thumb`,`mi_image`,`mi_descr`,`mi_custom_template`,`mi_enabled`,`mi_deleted`,`mi_access`,`mi_forlang`) VALUES('26','7','Правила пользования сайтом','0','window','0','','0','article','read','','pravila-polzovaniya-saytom','2','','','2','','','','','1','0','all','all')###qb_delimiter###
INSERT INTO `#__menus`(`mi_id`,`mi_parent_id`,`mi_name`,`mi_type`,`mi_target`,`mi_nofollow`,`mi_link`,`mi_canonical_id`,`mi_module`,`mi_view`,`mi_layout`,`mi_alias`,`mi_psid`,`mi_controller`,`mi_task`,`mi_ordering`,`mi_thumb`,`mi_image`,`mi_descr`,`mi_custom_template`,`mi_enabled`,`mi_deleted`,`mi_access`,`mi_forlang`) VALUES('25','1','Поиск по сайту','1','window','1','index.php?task=search','0','','','','','0','','','100','','','','','1','0','all','all')###qb_delimiter###
INSERT INTO `#__menus`(`mi_id`,`mi_parent_id`,`mi_name`,`mi_type`,`mi_target`,`mi_nofollow`,`mi_link`,`mi_canonical_id`,`mi_module`,`mi_view`,`mi_layout`,`mi_alias`,`mi_psid`,`mi_controller`,`mi_task`,`mi_ordering`,`mi_thumb`,`mi_image`,`mi_descr`,`mi_custom_template`,`mi_enabled`,`mi_deleted`,`mi_access`,`mi_forlang`) VALUES('23','1','Карта сайта','0','window','0','','0','site','map','','','0','','','99','','','','','1','0','all','all')###qb_delimiter###
INSERT INTO `#__menus`(`mi_id`,`mi_parent_id`,`mi_name`,`mi_type`,`mi_target`,`mi_nofollow`,`mi_link`,`mi_canonical_id`,`mi_module`,`mi_view`,`mi_layout`,`mi_alias`,`mi_psid`,`mi_controller`,`mi_task`,`mi_ordering`,`mi_thumb`,`mi_image`,`mi_descr`,`mi_custom_template`,`mi_enabled`,`mi_deleted`,`mi_access`,`mi_forlang`) VALUES('19','16','FAQ','0','window','0','','0','article','read','','kratkoe-rukovodstvo-administratora-po-rabote-s-sistemoy','46','','','0','','','','','1','0','all','all')###qb_delimiter###
INSERT INTO `#__menus`(`mi_id`,`mi_parent_id`,`mi_name`,`mi_type`,`mi_target`,`mi_nofollow`,`mi_link`,`mi_canonical_id`,`mi_module`,`mi_view`,`mi_layout`,`mi_alias`,`mi_psid`,`mi_controller`,`mi_task`,`mi_ordering`,`mi_thumb`,`mi_image`,`mi_descr`,`mi_custom_template`,`mi_enabled`,`mi_deleted`,`mi_access`,`mi_forlang`) VALUES('20','1','Галерея','0','window','0','','0','gallery','groups','','','0','','','70','','','','','1','0','all','all')###qb_delimiter###
INSERT INTO `#__menus`(`mi_id`,`mi_parent_id`,`mi_name`,`mi_type`,`mi_target`,`mi_nofollow`,`mi_link`,`mi_canonical_id`,`mi_module`,`mi_view`,`mi_layout`,`mi_alias`,`mi_psid`,`mi_controller`,`mi_task`,`mi_ordering`,`mi_thumb`,`mi_image`,`mi_descr`,`mi_custom_template`,`mi_enabled`,`mi_deleted`,`mi_access`,`mi_forlang`) VALUES('1','0','Верхнее меню','0','window','0','','0','','','','','0','','','10','','','','','1','0','all','all')###qb_delimiter###
INSERT INTO `#__menus`(`mi_id`,`mi_parent_id`,`mi_name`,`mi_type`,`mi_target`,`mi_nofollow`,`mi_link`,`mi_canonical_id`,`mi_module`,`mi_view`,`mi_layout`,`mi_alias`,`mi_psid`,`mi_controller`,`mi_task`,`mi_ordering`,`mi_thumb`,`mi_image`,`mi_descr`,`mi_custom_template`,`mi_enabled`,`mi_deleted`,`mi_access`,`mi_forlang`) VALUES('15','0','Видеоматериалы','0','window','1','','0','','','','','0','','','30','','','','','1','0','all','all')###qb_delimiter###
INSERT INTO `#__menus`(`mi_id`,`mi_parent_id`,`mi_name`,`mi_type`,`mi_target`,`mi_nofollow`,`mi_link`,`mi_canonical_id`,`mi_module`,`mi_view`,`mi_layout`,`mi_alias`,`mi_psid`,`mi_controller`,`mi_task`,`mi_ordering`,`mi_thumb`,`mi_image`,`mi_descr`,`mi_custom_template`,`mi_enabled`,`mi_deleted`,`mi_access`,`mi_forlang`) VALUES('16','0','Документация','0','window','1','','0','','','','','0','','','20','','','','','1','0','all','all')###qb_delimiter###
INSERT INTO `#__menus`(`mi_id`,`mi_parent_id`,`mi_name`,`mi_type`,`mi_target`,`mi_nofollow`,`mi_link`,`mi_canonical_id`,`mi_module`,`mi_view`,`mi_layout`,`mi_alias`,`mi_psid`,`mi_controller`,`mi_task`,`mi_ordering`,`mi_thumb`,`mi_image`,`mi_descr`,`mi_custom_template`,`mi_enabled`,`mi_deleted`,`mi_access`,`mi_forlang`) VALUES('10','1','Форум','0','window','0','','0','forum','','','','0','','','60','','','','','1','0','all','all')###qb_delimiter###
INSERT INTO `#__menus`(`mi_id`,`mi_parent_id`,`mi_name`,`mi_type`,`mi_target`,`mi_nofollow`,`mi_link`,`mi_canonical_id`,`mi_module`,`mi_view`,`mi_layout`,`mi_alias`,`mi_psid`,`mi_controller`,`mi_task`,`mi_ordering`,`mi_thumb`,`mi_image`,`mi_descr`,`mi_custom_template`,`mi_enabled`,`mi_deleted`,`mi_access`,`mi_forlang`) VALUES('21','1','Интернет-магазин','0','window','0','','0','catalog','','','','0','','','80','','','','','1','0','all','all')###qb_delimiter###
INSERT INTO `#__menus`(`mi_id`,`mi_parent_id`,`mi_name`,`mi_type`,`mi_target`,`mi_nofollow`,`mi_link`,`mi_canonical_id`,`mi_module`,`mi_view`,`mi_layout`,`mi_alias`,`mi_psid`,`mi_controller`,`mi_task`,`mi_ordering`,`mi_thumb`,`mi_image`,`mi_descr`,`mi_custom_template`,`mi_enabled`,`mi_deleted`,`mi_access`,`mi_forlang`) VALUES('7','1','Статьи','0','window','1','','0','article','list','','','0','','','10','','','','','1','0','all','all')###qb_delimiter###
INSERT INTO `#__menus`(`mi_id`,`mi_parent_id`,`mi_name`,`mi_type`,`mi_target`,`mi_nofollow`,`mi_link`,`mi_canonical_id`,`mi_module`,`mi_view`,`mi_layout`,`mi_alias`,`mi_psid`,`mi_controller`,`mi_task`,`mi_ordering`,`mi_thumb`,`mi_image`,`mi_descr`,`mi_custom_template`,`mi_enabled`,`mi_deleted`,`mi_access`,`mi_forlang`) VALUES('22','1','Видео','0','window','0','','0','videoset','groups','','','0','','','75','','','','','1','0','all','all')###qb_delimiter###
INSERT INTO `#__menus`(`mi_id`,`mi_parent_id`,`mi_name`,`mi_type`,`mi_target`,`mi_nofollow`,`mi_link`,`mi_canonical_id`,`mi_module`,`mi_view`,`mi_layout`,`mi_alias`,`mi_psid`,`mi_controller`,`mi_task`,`mi_ordering`,`mi_thumb`,`mi_image`,`mi_descr`,`mi_custom_template`,`mi_enabled`,`mi_deleted`,`mi_access`,`mi_forlang`) VALUES('6','1','Обратная связь','0','window','0','','0','feedback','message','','','0','','','50','','','','','1','0','all','all')###qb_delimiter###
INSERT INTO `#__menus`(`mi_id`,`mi_parent_id`,`mi_name`,`mi_type`,`mi_target`,`mi_nofollow`,`mi_link`,`mi_canonical_id`,`mi_module`,`mi_view`,`mi_layout`,`mi_alias`,`mi_psid`,`mi_controller`,`mi_task`,`mi_ordering`,`mi_thumb`,`mi_image`,`mi_descr`,`mi_custom_template`,`mi_enabled`,`mi_deleted`,`mi_access`,`mi_forlang`) VALUES('4','1','Новости','0','window','0','','0','blog','list','','novosti','1','','','20','','','','','0','0','all','all')###qb_delimiter###
INSERT INTO `#__menus`(`mi_id`,`mi_parent_id`,`mi_name`,`mi_type`,`mi_target`,`mi_nofollow`,`mi_link`,`mi_canonical_id`,`mi_module`,`mi_view`,`mi_layout`,`mi_alias`,`mi_psid`,`mi_controller`,`mi_task`,`mi_ordering`,`mi_thumb`,`mi_image`,`mi_descr`,`mi_custom_template`,`mi_enabled`,`mi_deleted`,`mi_access`,`mi_forlang`) VALUES('18','15','Уроки по BARMAZ-CMS','1','_blank','1','https://www.youtube.com/playlist?list=PL1GgrTeLgC00YwhIM0kYtGMnhXRdLKEm3','0','','','','','0','','','0','','','','','1','0','all','all')###qb_delimiter###
INSERT INTO `#__menus`(`mi_id`,`mi_parent_id`,`mi_name`,`mi_type`,`mi_target`,`mi_nofollow`,`mi_link`,`mi_canonical_id`,`mi_module`,`mi_view`,`mi_layout`,`mi_alias`,`mi_psid`,`mi_controller`,`mi_task`,`mi_ordering`,`mi_thumb`,`mi_image`,`mi_descr`,`mi_custom_template`,`mi_enabled`,`mi_deleted`,`mi_access`,`mi_forlang`) VALUES('29','7','О нас','0','window','0','','0','article','read','','o-proekte','1','','','1','','','','','1','0','all','all')###qb_delimiter###
INSERT INTO `#__menus`(`mi_id`,`mi_parent_id`,`mi_name`,`mi_type`,`mi_target`,`mi_nofollow`,`mi_link`,`mi_canonical_id`,`mi_module`,`mi_view`,`mi_layout`,`mi_alias`,`mi_psid`,`mi_controller`,`mi_task`,`mi_ordering`,`mi_thumb`,`mi_image`,`mi_descr`,`mi_custom_template`,`mi_enabled`,`mi_deleted`,`mi_access`,`mi_forlang`) VALUES('30','1','Обратный звонок','1','popup','1','index.php?module=feedback&amp;task=BackcallForm&amp;option=ajax','0','','','','','0','','','55','','','','','1','0','all','all')###qb_delimiter###
INSERT INTO `#__menus`(`mi_id`,`mi_parent_id`,`mi_name`,`mi_type`,`mi_target`,`mi_nofollow`,`mi_link`,`mi_canonical_id`,`mi_module`,`mi_view`,`mi_layout`,`mi_alias`,`mi_psid`,`mi_controller`,`mi_task`,`mi_ordering`,`mi_thumb`,`mi_image`,`mi_descr`,`mi_custom_template`,`mi_enabled`,`mi_deleted`,`mi_access`,`mi_forlang`) VALUES('31','0','Скрытое меню','0','window','0','','0','','','','','0','','','0','','','','','1','0','all','all')###qb_delimiter###
INSERT INTO `#__menus`(`mi_id`,`mi_parent_id`,`mi_name`,`mi_type`,`mi_target`,`mi_nofollow`,`mi_link`,`mi_canonical_id`,`mi_module`,`mi_view`,`mi_layout`,`mi_alias`,`mi_psid`,`mi_controller`,`mi_task`,`mi_ordering`,`mi_thumb`,`mi_image`,`mi_descr`,`mi_custom_template`,`mi_enabled`,`mi_deleted`,`mi_access`,`mi_forlang`) VALUES('32','31','Главная страница','0','window','0','','0','site','','','','0','','','0','','','','','1','0','all','all')###qb_delimiter###
INSERT INTO `#__menus`(`mi_id`,`mi_parent_id`,`mi_name`,`mi_type`,`mi_target`,`mi_nofollow`,`mi_link`,`mi_canonical_id`,`mi_module`,`mi_view`,`mi_layout`,`mi_alias`,`mi_psid`,`mi_controller`,`mi_task`,`mi_ordering`,`mi_thumb`,`mi_image`,`mi_descr`,`mi_custom_template`,`mi_enabled`,`mi_deleted`,`mi_access`,`mi_forlang`) VALUES('34','27','Политика конфиденциальности','0','window','0','','0','article','read','','politika-konfidentsialnosti','3','','','0','','','','','1','0','all','')###qb_delimiter###
INSERT INTO `#__menus`(`mi_id`,`mi_parent_id`,`mi_name`,`mi_type`,`mi_target`,`mi_nofollow`,`mi_link`,`mi_canonical_id`,`mi_module`,`mi_view`,`mi_layout`,`mi_alias`,`mi_psid`,`mi_controller`,`mi_task`,`mi_ordering`,`mi_thumb`,`mi_image`,`mi_descr`,`mi_custom_template`,`mi_enabled`,`mi_deleted`,`mi_access`,`mi_forlang`) VALUES('35','31','Личный кабинет','0','window','0','','0','user','','','','0','','','0','','','','','1','0','all','')###qb_delimiter###
INSERT INTO `#__menus`(`mi_id`,`mi_parent_id`,`mi_name`,`mi_type`,`mi_target`,`mi_nofollow`,`mi_link`,`mi_canonical_id`,`mi_module`,`mi_view`,`mi_layout`,`mi_alias`,`mi_psid`,`mi_controller`,`mi_task`,`mi_ordering`,`mi_thumb`,`mi_image`,`mi_descr`,`mi_custom_template`,`mi_enabled`,`mi_deleted`,`mi_access`,`mi_forlang`) VALUES('36','29','Тестовая статья','0','window','0','','0','article','read','','testovaya-statya','65','','','0','','','','','1','0','all','')###qb_delimiter###
INSERT INTO `#__menus`(`mi_id`,`mi_parent_id`,`mi_name`,`mi_type`,`mi_target`,`mi_nofollow`,`mi_link`,`mi_canonical_id`,`mi_module`,`mi_view`,`mi_layout`,`mi_alias`,`mi_psid`,`mi_controller`,`mi_task`,`mi_ordering`,`mi_thumb`,`mi_image`,`mi_descr`,`mi_custom_template`,`mi_enabled`,`mi_deleted`,`mi_access`,`mi_forlang`) VALUES('37','1','Тест','2','window','0','','21','','','','','0','','','0','','','','','1','0','all','')###qb_delimiter###


