TRUNCATE TABLE `#__widgets_active`###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('10','usermenu','Кабинет','1','','right-top','cabinet-menu','Widget_ID{=}widget_10{;}show_greeting{=}1{;}login_popup{=}1{;}show_register{=}1{;}show_reminder{=}1{;}show_post{=}1{;}show_basket{=}1{;}basket_popup{=}1{;}show_admin{=}1','all','','260','all','0','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('16','menu','Меню в шапке','0','','top-menu','menu navbar navbar-default','Widget_ID{=}widget_16{;}Title_tag{=}div{;}Collapse_widget{=}2{;}Collapsed_widget_title{=}Навигация{;}Hide_main_title_on_mobiles{=}1{;}Render_type{=}2{;}Hover_dropdown{=}1{;}Expand_active{=}0{;}Menu_ID{=}{;}Menu_class{=}navbar-nav{;}Menu_li_class{=}{;}Menu_a_class{=}{;}Menu_ul_class{=}{;}Menu_data_toggle_separate{=}1{;}Menu_root_id{=}1{;}Menu_max_levels{=}0{;}Hide_menu_titles{=}0{;}Translate{=}0','all','','210','all','0','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('19','catalogmenu','Товары и услуги','1','','right-top','menu','Widget_ID{=}widget_19{;}Title_tag{=}div{;}Collapse_widget{=}1{;}Collapsed_widget_title{=}Товары и услуги{;}Hide_main_title_on_mobiles{=}1{;}Menu_ID{=}{;}UL_class{=}{;}Order_by{=}ggr_name{;}Render_type{=}4{;}Hover_dropdown{=}0{;}Menu_data_toggle_separate{=}1{;}Expand_active{=}1{;}Exclude_groups_ids{=}{;}Max_levels{=}5{;}Root_id{=}0{;}Use_controller{=}default{;}Cart_button{=}1{;}Filter_button{=}1{;}Vendors_button{=}1{;}Manufacturers_button{=}1{;}Favourites_button{=}1{;}Compare_button{=}1','all','','200','all','0','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('20','customHTML','Счетчик','0','','user-9','counters','Widget_ID{=}widget_20{;}Title_tag{=}div{;}Translate{=}0','all','<img width=\"88\" height=\"31\" src=\"/images/counter_example.png\" alt=\"Рейтинг\" />','220','all','15','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('61','menu','Документация','1','','center-bottom','b_half','Widget_ID{=}widget_61{;}Title_tag{=}div{;}Collapse_widget{=}0{;}Collapsed_widget_title{=}{;}Hide_main_title_on_mobiles{=}1{;}Render_type{=}0{;}Hover_dropdown{=}0{;}Menu_ID{=}{;}Menu_class{=}nav nav-pills nav-stacked{;}Menu_li_class{=}{;}Menu_a_class{=}{;}Menu_ul_class{=}{;}Menu_data_toggle_separate{=}0{;}Menu_root_id{=}16{;}Menu_max_levels{=}0{;}Hide_menu_titles{=}0{;}Translate{=}0','all','','90','all','0','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('62','menu','Видеоматериалы','1','','center-bottom','b_half','Widget_ID{=}widget_62{;}Title_tag{=}div{;}Collapse_widget{=}0{;}Collapsed_widget_title{=}{;}Hide_main_title_on_mobiles{=}1{;}Render_type{=}0{;}Hover_dropdown{=}0{;}Menu_ID{=}{;}Menu_class{=}nav nav-pills nav-stacked{;}Menu_li_class{=}{;}Menu_a_class{=}{;}Menu_ul_class{=}{;}Menu_data_toggle_separate{=}0{;}Menu_root_id{=}15{;}Menu_max_levels{=}0{;}Hide_menu_titles{=}0{;}Translate{=}0','all','','110','all','0','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('63','randarticle','Случайная статья','1','','right-bottom','','Widget_ID{=}widget_63{;}Title_tag{=}div{;}ParentarticleId{=}46{;}ShowDopTitle{=}0{;}DopTitle{=}{;}LinkDopTitle{=}{;}shortTextLength{=}200','all','','130','32','15','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('26','acrm','Верхние баннеры','0','','top','items_1 float-fix','Widget_ID{=}top_1{;}Client_ID{=}1{;}Category_ID{=}1{;}Quantity{=}5{;}Show_titles{=}0{;}Show_descriptions{=}0{;}Randomize{=}0','all','','230','except;32','30','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('30','blogpost','Последние новости','1','','right-top','','Widget_ID{=}widget_30{;}Title_tag{=}div{;}blog_Id{=}1;4{;}blog_Id_ex{=}4{;}post_count{=}5{;}show_date{=}1{;}show_time_in_date{=}1{;}show_post_title{=}1{;}brief_length{=}0{;}show_readmore{=}1{;}show_thumb{=}1{;}sort_by_touchdate{=}0{;}show_all_blog_id{=}1{;}show_all_blog_text{=}{;}data_absent_text{=}{;}menu_id{=}4','all','','240','all','15','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('31','polls','Наш опрос','1','','left-bottom','','Widget_ID{=}plll{;}Poll_ID{=}14{;}Poll_results{=}1{;}All_polls_button{=}1{;}Show_bars{=}1{;}Bar_color_hex{=}#FF0000','all','','145','32;29;26;27;28','1','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('55','acrm','Нижние баннеры','0','','bottom','items_2 float-fix','Widget_ID{=}btm_1{;}Client_ID{=}1{;}Category_ID{=}1{;}Quantity{=}4{;}Show_titles{=}0{;}Show_descriptions{=}0{;}Randomize{=}0','all','','0','all','30','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('64','randgoods','Товар часа','1','','left-bottom','','Widget_ID{=}widget_64{;}Title_tag{=}div{;}ShowDopTitle{=}1{;}DopTitle{=}{;}LinkDopTitle{=}{;}goodsGroupid{=}149{;}goodsid{=}0{;}onlyNew{=}0{;}onlyHit{=}0{;}showDescription{=}0{;}shortTextLength{=}200','all','','150','32','0','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('65','remotegoods','Товар с другого сайта','1','','left-bottom','','Widget_ID{=}widget_65{;}Title_tag{=}div{;}ShowDopTitle{=}1{;}DopTitle{=}Наши партнеры{;}LinkDopTitle{=}{;}RemoteURL{=}http://BARMAZ-cms.web/{;}RemoteQuery{=}module=catalog&amp;option=ajax&amp;task=getRandomGoods{;}BannerID{=}15{;}RequestTimeout{=}5{;}shortTextLength{=}200','all','','160','all','0','0','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('66','breadcrumb','Хлебные крошки','0','','user-1','w_breadcrumb','Widget_ID{=}widget_66{;}Show_first_separator{=}0','all','','170','all','0','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('72','basket','Корзина','1','','right-top','','Widget_ID{=}my_mini_basket{;}Basket_ID{=}ajax_basket','all','','180','all','0','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('71','catalogfilter','Фильтр товаров','1','','right-top','','Widget_ID{=}widget_71{;}Title_tag{=}div{;}Collapse_widget{=}2{;}Collapsed_widget_title{=}Фильтр{;}Hide_main_title_on_mobiles{=}1{;}Filter_ID{=}CustomCatalogFilter{;}Hide_filter_panel{=}0{;}Show_own_filter_panel{=}1{;}Show_switch_filter_mode_button{=}1{;}max_checkbox_per_parameter{=}3{;}Show_on_level{=}2{;}Use_GET_form_method{=}1{;}Use_counter_for_fields{=}1{;}Use_experimental_functions{=}1','all','','190','21','0','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('73','gallery','Фотогалерея','1','','left-bottom','','Widget_ID{=}widget_73{;}Title_tag{=}div{;}gallery_id{=}3{;}images_count{=}6{;}gw_quadro_by_row{=}4','all','','120','4;22','0','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('74','blogcalendar','Календарь','1','','right-top','','Widget_ID{=}widget_74{;}blog_id{=}1{;}menu_id{=}4','all','','100','4','0','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('75','search','Поиск','0','','right-top','','Widget_ID{=}widget_75{;}Title_tag{=}div{;}search_type{=}blogs_posts{;}show_label{=}0{;}show_button{=}1{;}text_in_field{=}Поиск по сайту...{;}minimum_search_length{=}3','all','','80','except;21','30','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('76','tagscloud','Облако тегов','1','','right-top','','Widget_ID{=}widget_76{;}Title_tag{=}div{;}min_font_size{=}12{;}max_font_size{=}18{;}max_tags_show{=}20{;}show_quantity{=}1{;}links_nofollow{=}1{;}tags_type{=}blog','all','','20','except;21','0','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('79','forumpost','Новые сообщения в темах','1','','left-top','','Widget_ID{=}widget_79{;}Title_tag{=}div{;}forum_Id{=}1;2;3;4{;}forum_Id_ex{=}{;}post_count{=}5{;}show_author{=}1{;}show_date{=}1{;}add_nofollow{=}1{;}menu_id{=}10','all','','30','except;21','0','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('80','menu','Левое меню','0','','left-top','menu','Widget_ID{=}widget_80{;}Title_tag{=}div{;}Collapse_widget{=}2{;}Collapsed_widget_title{=}Меню сайта{;}Hide_main_title_on_mobiles{=}1{;}Render_type{=}2{;}Hover_dropdown{=}0{;}Menu_ID{=}{;}Menu_class{=}{;}Menu_li_class{=}{;}Menu_a_class{=}{;}Menu_ul_class{=}{;}Menu_data_toggle_separate{=}1{;}Menu_root_id{=}1{;}Menu_max_levels{=}0{;}Hide_menu_titles{=}0{;}Translate{=}0','all','','40','except;21','0','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('81','goods','Наши товары','0','','user-1','','Widget_ID{=}catalog_hits{;}Title_tag{=}div{;}ShowDopTitle{=}0{;}DopTitle{=}{;}LinkDopTitle{=}{;}goodsGroupid{=}0{;}goodsQuantity{=}6{;}goods_in_row{=}6{;}showSKU{=}0{;}showCustomProperties{=}1{;}onlyNew{=}0{;}onlyHit{=}0{;}orderBy{=}g_name.ASC{;}showCartButton{=}1{;}showCatalogButton{=}0{;}showFavouritesButton{=}1{;}showCompareButton{=}1{;}catalogButtonText{=}Перейти в каталог','all','','50','32','0','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('82','acrm_slider','Слайдер баннеров','0','','top','','Widget_ID{=}widget_82{;}Title_tag{=}div{;}Client_ID{=}1{;}Category_ID{=}2{;}Show_banner_description{=}0{;}Show_navs{=}2{;}Show_controls{=}1{;}Slide_effect{=}scroll{;}Interval{=}5','all','','70','32','0','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('83','customHTML','Предупреждение о ДЕМО-версии сайта','0','','user-1','','Widget_ID{=}widget_83{;}Translate{=}0','all','<font color=\"#FF0000\">
<center>ВНИМАНИЕ !!! ЭТОТ САЙТ ЯВЛЯЕТСЯ ДЕМОНСТРАЦИОННЫМ.</center>
<center>ЛЮБЫЕ ПОКУПКИ СОВЕРШАЕМЫЕ НА ДАННОМ САЙТЕ НЕ ЯВЛЯЮТСЯ РЕАЛЬНЫМИ.</center>
<center style=\"height: 10px;\">&nbsp;</center>
</font>','10','all','0','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('84','catalogsearch','Поиск по каталогу','0','','top','catalog-search','Widget_ID{=}widget_84{;}Title_tag{=}div{;}show_label{=}0{;}show_button{=}1{;}controller_name{=}default{;}text_in_field{=}Поиск по каталогу...','all','','50','all','0','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('85','menu','Документация','1','','user-7','footer-menu','Widget_ID{=}widget_85{;}Title_tag{=}div{;}Menu_ID{=}{;}Menu_class{=}{;}Menu_li_class{=}{;}Menu_a_class{=}{;}Menu_ul_class{=}{;}Menu_root_id{=}16{;}Menu_max_levels{=}0{;}Hide_menu_titles{=}0{;}Render_type{=}0{;}Translate{=}0','all','','0','all','0','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('86','menu','Видеоматериалы','1','','user-8','footer-menu','Widget_ID{=}widget_86{;}Title_tag{=}div{;}Menu_ID{=}{;}Menu_class{=}{;}Menu_li_class{=}{;}Menu_a_class{=}{;}Menu_ul_class{=}{;}Menu_root_id{=}15{;}Menu_max_levels{=}0{;}Hide_menu_titles{=}0{;}Render_type{=}0{;}Translate{=}0','all','','0','all','0','1','0','all')###qb_delimiter###
INSERT INTO `#__widgets_active`(`aw_id`,`aw_name`,`aw_title`,`aw_show_title`,`aw_title_link`,`aw_zone`,`aw_class`,`aw_config`,`aw_access`,`aw_content`,`aw_ordering`,`aw_visible_in`,`aw_cache`,`aw_enabled`,`aw_deleted`,`aw_forlang`) VALUES('88','menu','Тестовое меню','1','','right-top','','Widget_ID{=}widget_88{;}Title_tag{=}div{;}Collapse_widget{=}1{;}Collapsed_widget_title{=}тест-тест{;}Hide_main_title_on_mobiles{=}1{;}Render_type{=}1{;}Hover_dropdown{=}0{;}Expand_active{=}1{;}Menu_ID{=}{;}Menu_class{=}{;}Menu_li_class{=}{;}Menu_a_class{=}{;}Menu_ul_class{=}{;}Menu_data_toggle_separate{=}0{;}Menu_root_id{=}1{;}Menu_max_levels{=}0{;}Hide_menu_titles{=}0{;}Translate{=}0','all','','0','all','0','0','0','all')###qb_delimiter###


