DROP TABLE IF EXISTS `#__menus`###qb_delimiter###
CREATE TABLE `#__menus` (
  `mi_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `mi_parent_id` int(11) NOT NULL,
  `mi_name` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `mi_type` int(11) NOT NULL DEFAULT '0',
  `mi_target` varchar(20) NOT NULL DEFAULT 'window',
  `mi_nofollow` tinyint(1) NOT NULL DEFAULT '0',
  `mi_link` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `mi_canonical_id` int(11) NOT NULL DEFAULT '0',
  `mi_module` varchar(100) NOT NULL DEFAULT '',
  `mi_view` varchar(100) NOT NULL DEFAULT '',
  `mi_layout` varchar(100) NOT NULL DEFAULT '',
  `mi_alias` varchar(250) NOT NULL DEFAULT '',
  `mi_psid` int(11) NOT NULL DEFAULT '0',
  `mi_controller` varchar(100) NOT NULL DEFAULT '',
  `mi_task` varchar(100) NOT NULL DEFAULT '',
  `mi_ordering` smallint(3) NOT NULL DEFAULT '10',
  `mi_thumb` varchar(255) NOT NULL DEFAULT '',
  `mi_image` varchar(255) NOT NULL DEFAULT '',
  `mi_descr` text NOT NULL,
  `mi_custom_template` varchar(255) NOT NULL DEFAULT '',
  `mi_enabled` smallint(1) NOT NULL DEFAULT '1',
  `mi_deleted` smallint(1) NOT NULL DEFAULT '0',
  `mi_access` text NOT NULL COMMENT 'уровень доступа',
  `mi_forlang` varchar(255) DEFAULT 'all' COMMENT 'for which languages is menu item',
  PRIMARY KEY (`mi_id`),
  KEY `mi_deleted` (`mi_deleted`),
  KEY `mi_enabled` (`mi_enabled`)
) ENGINE=MyISAM AUTO_INCREMENT=38 DEFAULT CHARSET=utf8 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC###qb_delimiter###

